---
version: '3.8'

services:
  tetris:
    build: .
    container_name: tetris_app
    command:  python /u06_tetris/main_modified.py


    # User docker-compose build
    # ==> docker-compose up -d
    # check logs, docker-compose logs web, see that uvicorn started.

